Improve backlight script

diff --git a/misc/adjust-backlight b/misc/adjust-backlight
--- a/misc/adjust-backlight
+++ b/misc/adjust-backlight
@@ -30,32 +30,34 @@ cd "$backlight" || die "failed to change to $backlight folder."
 
 max_brightness=$(cat max_brightness)
 
-echo "Current brightness: $(cat brightness)/$max_brightness."
+while true; do
+  echo "Current brightness: $(cat brightness)/$max_brightness."
 
-brightness="$(cat brightness)"
+  brightness="$(cat brightness)"
 
-(( brightness >= 10 )) || die "current brightness ($brightness) is not adjustable."
+  (( brightness >= 10 )) || die "current brightness ($brightness) is not adjustable."
 
-echo
-echo "Select new brightness level relative to current (the smaller, the darker):"
+  echo
+  echo "Select new brightness level relative to current (the smaller, the darker):"
 
-select level in "150%" "125%" "75%" "66%" "50%" "33%" "25%"; do
-  case "$level" in
-   "150%") new_brightness=$(( brightness*3/2 )); break ;;
-   "125%") new_brightness=$(( brightness*5/4 )); break ;;
-    "75%") new_brightness=$(( brightness*3/4 )); break ;;
-    "66%") new_brightness=$(( brightness*2/3 )); break ;;
-    "50%") new_brightness=$(( brightness/2   )); break ;;
-    "33%") new_brightness=$(( brightness/3   )); break ;;
-    "25%") new_brightness=$(( brightness/4   )); break ;;
-        *) die "invalid option selected."              ;;
-  esac
+  select level in "150%" "125%" "75%" "66%" "50%" "33%" "25%"; do
+    case "$level" in
+     "150%") new_brightness=$(( brightness*3/2 )); break ;;
+     "125%") new_brightness=$(( brightness*5/4 )); break ;;
+      "75%") new_brightness=$(( brightness*3/4 )); break ;;
+      "66%") new_brightness=$(( brightness*2/3 )); break ;;
+      "50%") new_brightness=$(( brightness/2   )); break ;;
+      "33%") new_brightness=$(( brightness/3   )); break ;;
+      "25%") new_brightness=$(( brightness/4   )); break ;;
+          *) die "invalid option selected."              ;;
+    esac
+  done
+
+  (( new_brightness >= 10 )) || die "new brightness level ($new_brightness) is too low."
+  (( new_brightness < max_brightness )) || die "new brightness level ($new_brightness) is too high."
+
+  echo "Setting brightness level to: $new_brightness."
+  echo "(you may be asked for admin password)"
+
+  sudo su -c "echo $new_brightness > brightness"
 done
-
-(( new_brightness >= 10 )) || die "new brightness level ($new_brightness) is too low."
-(( new_brightness < max_brightness )) || die "new brightness level ($new_brightness) is too high."
-
-echo "Setting brightness level to: $new_brightness."
-echo "(you may be asked for admin password)"
-
-sudo su -c "echo $new_brightness > brightness"
